version: '3.3'
services:
  mysql:
    container_name: db
    image: docker.io/mysql:8.0
    restart: always
    volumes:
      - ./script:/docker-entrypoint-initdb.d/
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Kim-254500

  backend:
    container_name: backend
    image: quay.io/chisanuchakim/plutocart_backend
    restart: on-failure
    depends_on:
      - mysql